on:
  workflow_dispatch:

name: Build

jobs:
  build_and_test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.85.0
        with:
          components: rustfmt
      - run: cargo build --release --all-features
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-blockless-runtime
          path: |
            target/release
            !target/release/build
            !target/release/deps
            !target/release/examples
            !target/release/incremental
