name: Code coverage with grcov

on:
  pull_request:
    branches:
      - main

jobs:
  grcov:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@1.85.0
        with:
          components: rustfmt

      - name: Install LLVM tools
        run: |
          rustup component add llvm-tools-preview
          curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-x86_64-unknown-linux-gnu.tar.bz2 | tar jxf -

      - name: Cache cargo dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Execute tests for coverage
        run: |
          cargo test --all --all-features
        env:
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: "-Ccodegen-units=1 -Clink-dead-code -Coverflow-checks=off -Cinstrument-coverage"
          LLVM_PROFILE_FILE: "coverage-%p-%m.profraw"

      - name: Debug coverage files
        run: |
          echo "Listing all profraw files:"
          find . -name "*.profraw" -ls || echo "No profraw files found"
          echo "Checking target/debug directory:"
          ls -la target/debug/deps/ || echo "No target/debug/deps directory"

      - name: Generate coverage report
        run: |
          ./grcov . \
            --binary-path ./target/debug/deps/ \
            -s . \
            -t lcov \
            --branch \
            --ignore-not-existing \
            --ignore "/*" \
            --ignore "tests/*" \
            --ignore "target/*" \
            --filter covered \
            --llvm \
            -o lcov.info

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: lcov.info
