name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
env:
  CARGO_TERM_COLOR: always

jobs:
  fmt-clippy-check-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: rustup override set nightly
      - run: cargo fmt --all -- --check
      - run: rustup component add clippy
      - run: cargo clippy --all-features --all-targets -- -D warnings
      - run: cargo check --release --all --all-features
      - run: cargo test --all --all-features
